### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "dfcaf4e8bd6c4d819ac661752db3ceb7",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transacton
GET http://localhost:8080/transaction/c4aee66a11d24edcb4a4252177da6d8b